### ISSUE TITLE
cors hatası

### ISSUE THREAD

**Issue by zafer06** [melihkorkmaz/il-ilce-mahalle-geolocation-rest-api#12]
axios veya fetch api ile "https://il-ilce-rest-api.herokuapp.com/v1/cities" adresinden veri almaya çalıştığımda aşağıdaki hatayı alıyorum.

 ``` Access to fetch at 'https://il-ilce-rest-api.herokuapp.com/v1/cities' from origin 'http://127.0.0.1:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.```

**Comment by Pasinli** [comment]
` var proxyUrl = 'https://cors-anywhere.herokuapp.com/',
 targetUrl = 'https://il-ilce-rest-api.herokuapp.com/v1/cities'
fetch(proxyUrl + targetUrl)
  .then(blob => blob.json())
  .then(data => {
    return data;
  })
  .catch(e => {
    return e;
  });`

**Comment by zafer06** [comment]
Teşekkürler @Pasinli gönderdiğin kodlar işe yaradı. Ancak merak ediyorum bu soruna api tarafında bir çözüm bulunması daha doğru olmaz mıydı?
