### ISSUE TITLE
servis çalışmıyor

### ISSUE THREAD

**Issue by sekmenhuseyin** [melihkorkmaz/il-ilce-mahalle-geolocation-rest-api#3]
http://geoapi.sanalonyedi.net/v1 çalışmıyor

**Comment by melihkorkmaz** [comment]
Sonuç dönüyor gibi görünüyor ama şu adresi dener misiniz?

http://geoapi.sanalonyedi.net/v1/cities

**Comment by sekmenhuseyin** [comment]
teşekkürler

**Comment by suleymanccelik** [comment]
@melihkorkmaz hocam servisin durumunu kontrol edebilir misin? Teşekkürler.
